sudo: false
dist: trusty
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"


env:
  global:
    - PYPI_VENDOR_DIR='./tests/pypi/'
    - GIT_ASK_YESNO='false'
  addons:
    apt:
      packages:
        - libatlas-dev
        - libatlas3gf-base

  matrix:
    - TEST_SUITE='not install'
    - TEST_SUITE='install'
      PYTEST_ADDOPTS='--cache-clear'

install:
  - "pip install --upgrade pip"
  - "pip install pipenv==11.10.0" # temporary while bug #2120 fix
  - "pipenv install --dev"
  - "pip install --no-deps --force --upgrade ."

script:
   - "pytest mcmodels"
