sudo: false
dist: trusty
language: python
python:
  - "3.6"


env:
  global:
    - PYPI_VENDOR_DIR='./tests/pypi/'
    - GIT_ASK_YESNO='false'
  addons:
    apt:
      packages:
        - libatlas-dev
        - libatlas3gf-base

install:
  - pip install --upgrade pip
  - pip install pipenv==11.10.0 # temporary while pipenv bug #2120 fix
  - pipenv install --dev
  - pipenv run python -m pip install pytest pytest-cov codecov --upgrade

before_script:
  - pipenv run python -m pip install .

script:
  - pipenv run python -m pytest --cov=mcmodels
    # do not fail build if upload to codecov fails
  - codecov || echo "codecov upload failed"
